/*
 * MIT License
 *
 * Copyright (c) 2025-2026  Yurii Yakubin (yurii.yakubin@gmail.com)
 *
 * Permission is granted to use, copy, modify, and distribute this software
 * under the MIT License. See LICENSE file for details.
 */

#ifndef _LIBNETQ_DBC_DBCKEYWORDS_H
#define _LIBNETQ_DBC_DBCKEYWORDS_H

#define NQDBC_KEYWORD_MAX (32u)
typedef char NQDBCKeyword[NQDBC_KEYWORD_MAX];

enum DBCKeywordType {
  NQDBC_KEYWORD_VERSION,
  NQDBC_KEYWORD_NS,
  NQDBC_KEYWORD_BS,
  NQDBC_KEYWORD_BU,
  NQDBC_KEYWORD_BO,
  NQDBC_KEYWORD_BO_TX_BU,
  NQDBC_KEYWORD_EV,
  NQDBC_KEYWORD_ENVVAR_DATA,
  NQDBC_KEYWORD_CM,
  NQDBC_KEYWORD_BA,
  NQDBC_KEYWORD_BA_REL,
  NQDBC_KEYWORD_BA_DEF,
  NQDBC_KEYWORD_BA_DEF_REL,
  NQDBC_KEYWORD_BA_DEF_DEF,
  NQDBC_KEYWORD_BA_DEF_DEF_REL,
  NQDBC_KEYWORD_SG,
  NQDBC_KEYWORD_SGTYPE,
  NQDBC_KEYWORD_SG_MUL_VAL,
  NQDBC_KEYWORD_SIG_GROUP,
  NQDBC_KEYWORD_SIG_VALTYPE,
  NQDBC_KEYWORD_SIG_TYPE_REF,
  NQDBC_KEYWORD_VAL,
  NQDBC_KEYWORD_VAL_TABLE,
};

#endif /* _LIBNETQ_DBC_DBCKEYWORDS_H */
